taskmaster:
    my-program:
        workdir: "/var/lib/temp" 
        umask: "022"

        cmd: # allow the user to add args has much as he want 
            - "/usr/bin/my-program"
            - "-v"
        
        journey:
            autostart: true #boolean
            health-time: 1000 # in ms
        
            restart-policy:
                restart-case: "unexpected" # always, never, unexpected
                restart-nb: 3 # amount of restart before aborting the process

            exit: 
                code: [0] # list of exit code 
                signal: ["SIGTERM"] #list of signals that exit the process
                timeout-ms: 5000 # in ms 

        process-nb: 1 # the number of process we want to run

        output:
            stdout: "/dev/null"
            stderr: "/dev/null"
        env:
            APP_ENV: "prod"
            LOG_LEVEL: "info"
    my-program-2:
        workdir: "/var/lib/temp" 
        umask: "022"

        cmd: # allow the user to add args has much as he want 
            - "/usr/bin/my-program-2"
            - "-v"
        
        journey:
            autostart: true #boolean
            health-time: 1000 # in ms
        
            restart-policy:
                restart-case: "unexpected" # always, never, unexpected
                restart-nb: 3 # amount of restart before aborting the process

            exit: 
                code: [0] # list of exit code 
                signal: ["SIGTERM"] #list of signals that exit the process
                timeout-ms: 5000 # in ms 

        process-nb: 1 # the number of proccess we want to run

        output:
            stdout: "/dev/null"
            stderr: "/dev/null"
        env:
            APP_ENV: "prod"
            LOG_LEVEL: "info"

